import dash_html_components as html
from utils.html import button

layout = html.Div(
    [
        html.H1("Les boutons"),
        html.H2("Default"),
        html.H3("Large"),
        button("Default", size="large"),
        button("Disabled", size="large", disabled=True),
        html.Br(),
        button("Default", size="large"),
        button("Disabled", size="large", disabled=True),
        html.H3("Medium"),
        button("Default"),
        button("Disabled", disabled=True),
        html.Br(),
        button("Default"),
        button("Disabled", disabled=True),
        html.H3("Small"),
        button("Default", size="small"),
        button("Disabled", size="small", disabled=True),
        html.Br(),
        button("Default", size="small"),
        button("Disabled", size="small", disabled=True),
        html.Hr(),
        html.H2("Secondary"),
        html.H3("Large"),
        button("Default", kind="secondary", size="large"),
        button("Disabled", kind="secondary", size="large", disabled=True),
        html.Br(),
        button("Default", kind="secondary", size="large"),
        button("Disabled", kind="secondary", size="large", disabled=True),
        html.H3("Medium"),
        button("Default", kind="secondary"),
        button("Disabled", kind="secondary", disabled=True),
        html.Br(),
        button("Default", kind="secondary"),
        button("Disabled", kind="secondary", disabled=True),
        html.H3("Small"),
        button("Default", kind="secondary", size="small"),
        button("Disabled", kind="secondary", size="small", disabled=True),
        html.Br(),
        button("Default", kind="secondary", size="small"),
        button("Disabled", kind="secondary", size="small", disabled=True),
    ]
)
