OPTIONS_CANCER = [
    {"label": "Digestif bas", "value": "Digestif bas"},
    {"label": "Digestif haut", "value": "Digestif haut"},
    {"label": "Glioblastome", "value": "Glioblastome"},
    {"label": "Gynécologique", "value": "Gynécologique"},
    {"label": "Lymphome", "value": "Lymphome"},
    {"label": "Mélanome", "value": "Mélanome"},
    {"label": "Myélome", "value": "Myélome"},
    {"label": "ORL", "value": "ORL"},
    {"label": "Pancréas", "value": "Pancréas"},
    {"label": "Poumon", "value": "Poumon"},
    {"label": "Prostate", "value": "Prostate"},
    {"label": "Sein", "value": "Sein"},
    {"label": "Testicule", "value": "Testicule"},
    {"label": "Urothélial", "value": "Urothélial"},
]
